[package]
name = "binread"
version = "1.0.2"
authors = ["jam1garner <jam1.mcleod@hotmail.com>"]
edition = "2018"
repository = "https://github.com/jam1garner/binread"
license = "MIT"
description = "A Rust crate for helping read structs from binary data using ✨macro magic✨"
readme = "README.md"
documentation = "https://docs.rs/binread"

[dependencies]
#binread_derive = { git = "https://github.com/jam1garner/binread_derive" }
binread_derive = { version = "1.0", path = "../binread_derive" }
lazy_static = { version = "1.4" , optional=true }

[features]
default = ["std"]
std = []
debug_template = ["std", "lazy_static", "binread_derive/debug_template"]
