[package]
name = "binwrite_derive"
version = "0.1.0"
authors = ["jam1garner <jam1.mcleod@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.7", features = ["extra-traits"] }
quote = "1.0.2"
proc-macro2 = "1.0.6"
binwrite = { path = "../binwrite" }

[dev-dependencies]
binwrite = { path = "../binwrite" }

